<?php

namespace Sensorario\CommentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findOrderedFromlastToFirst($id)
    {
        return $this->createQueryBuilder('c')
                        ->orderBy('c.creation_date', 'desc')
                        ->where('c.unique_id = :unique_id')
                        ->setParameter('unique_id', $id)
                        ->getQuery()
                        ->getResult();
    }

}