<?php

namespace Sensorario\CommentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findOrderedFromlastToFirst()
    {
        return $this->createQueryBuilder('c')
                        ->orderBy('c.creation_date', 'desc')
                        ->getQuery()
                        ->getResult();
    }

}